# Generated by Django 3.2.2 on 2021-05-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zzprojectyrod', '0003_license_keys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='License_keys',
            new_name='LicenseKeys',
        ),
    ]
